version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - airi
  - Attributify
  - attw
  - Ayaka
  - bigserial
  - bumpp
  - changelogithub
  - defu
  - guiiai
  - logg
  - Neko
  - nekw
  - pglite
  - rspack
  - taze
  - tsdown
  - uncrypto
  - unocss
  - unplugin
  - vueuse
ignoreWords: []
import: []
